"""Add channelName to Clip

Revision ID: 6f97a37272b1
Revises: d1bb6de2e92b
Create Date: 2025-12-13 13:50:00.657988

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '6f97a37272b1'
down_revision: Union[str, Sequence[str], None] = 'd1bb6de2e92b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('clip', sa.Column('channelName', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    op.alter_column('clip', 'uploadDate',
               existing_type=sa.TEXT(),
               type_=sqlmodel.sql.sqltypes.AutoString(),
               existing_nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('clip', 'uploadDate',
               existing_type=sqlmodel.sql.sqltypes.AutoString(),
               type_=sa.TEXT(),
               existing_nullable=True)
    op.drop_column('clip', 'channelName')
    # ### end Alembic commands ###
