"""Add outlier score fields final

Revision ID: 2ab388ca74e8
Revises: 4106d5e2c475
Create Date: 2025-12-20 14:55:46.320933

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2ab388ca74e8'
down_revision: Union[str, Sequence[str], None] = '4106d5e2c475'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('clip', sa.Column('outlierScore', sa.Float(), nullable=True))
    op.add_column('clip', sa.Column('channelAverageViews', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('clip', 'channelAverageViews')
    op.drop_column('clip', 'outlierScore')
    # ### end Alembic commands ###
