"""Add ideation features

Revision ID: 3811d2cf703d
Revises: a56b7c22346f
Create Date: 2025-12-16 20:06:17.475947

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3811d2cf703d'
down_revision: Union[str, Sequence[str], None] = 'a56b7c22346f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('videoideation',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('projectName', sa.VARCHAR(), nullable=False),
    sa.Column('mainIdea', sa.Text(), nullable=True),
    sa.Column('whyViewerCare', sa.Text(), nullable=True),
    sa.Column('commonAssumptions', sa.Text(), nullable=True),
    sa.Column('breakingAssumptions', sa.Text(), nullable=True),
    sa.Column('viewerFeeling', sa.Text(), nullable=True),
    sa.Column('brainstormedTitles', sa.Text(), nullable=True),
    sa.Column('brainstormedThumbnails', sa.Text(), nullable=True),
    sa.Column('scriptOutline', sa.Text(), nullable=True),
    sa.Column('scriptContent', sa.Text(), nullable=True),
    sa.Column('createdAt', sa.BigInteger(), nullable=False),
    sa.Column('updatedAt', sa.BigInteger(), nullable=False),
    sa.Column('user_id', sa.Uuid(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.add_column('clip', sa.Column('scriptOutline', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('clip', 'scriptOutline')
    op.drop_table('videoideation')
    # ### end Alembic commands ###
