"""Add spaces

Revision ID: 4106d5e2c475
Revises: 98fc13ea3d84
Create Date: 2025-12-18 15:37:30.177596

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4106d5e2c475'
down_revision: Union[str, Sequence[str], None] = '98fc13ea3d84'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('clip', sa.Column('space_id', sa.Uuid(), nullable=True))
    op.create_foreign_key(None, 'clip', 'space', ['space_id'], ['id'])
    op.add_column('note', sa.Column('space_id', sa.Uuid(), nullable=True))
    op.create_foreign_key(None, 'note', 'space', ['space_id'], ['id'])
    op.add_column('tag', sa.Column('space_id', sa.Uuid(), nullable=True))
    op.create_foreign_key(None, 'tag', 'space', ['space_id'], ['id'])
    op.add_column('videoideation', sa.Column('space_id', sa.Uuid(), nullable=True))
    op.create_foreign_key(None, 'videoideation', 'space', ['space_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'videoideation', type_='foreignkey')
    op.drop_column('videoideation', 'space_id')
    op.drop_constraint(None, 'tag', type_='foreignkey')
    op.drop_column('tag', 'space_id')
    op.drop_constraint(None, 'note', type_='foreignkey')
    op.drop_column('note', 'space_id')
    op.drop_constraint(None, 'clip', type_='foreignkey')
    op.drop_column('clip', 'space_id')
    # ### end Alembic commands ###
