"""add_cancellation_fields

Revision ID: 49411765d07a
Revises: a75938c1eeed
Create Date: 2025-12-18 13:21:38.159224

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '49411765d07a'
down_revision: Union[str, Sequence[str], None] = 'a75938c1eeed'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('cancel_at_period_end', sa.Boolean(), server_default=sa.text('false'), nullable=False))
    op.add_column('user', sa.Column('current_period_end', sa.BigInteger(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'current_period_end')
    op.drop_column('user', 'cancel_at_period_end')
    # ### end Alembic commands ###
