"""add_audience_and_vibe_to_video_ideation

Revision ID: 4aa773e21e0c
Revises: c8ab64aad7e3
Create Date: 2026-01-28 11:02:40.322450

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4aa773e21e0c'
down_revision: Union[str, Sequence[str], None] = 'c8ab64aad7e3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('videoideation', sa.Column('targetAudience', sa.Text(), nullable=True))
    op.add_column('videoideation', sa.Column('visualVibe', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('videoideation', 'visualVibe')
    op.drop_column('videoideation', 'targetAudience')
    # ### end Alembic commands ###
