"""add_unique_constraint_clips

Revision ID: 77d8882e49ce
Revises: f03eb7b52ec9
Create Date: 2026-01-25 18:51:14.157741

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '77d8882e49ce'
down_revision: Union[str, Sequence[str], None] = 'f03eb7b52ec9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint('unique_clip_video_space', 'clip', ['videoId', 'space_id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('unique_clip_video_space', 'clip', type_='unique')
    # ### end Alembic commands ###
