"""remove folder model and relationships

Revision ID: 98fc13ea3d84
Revises: 49411765d07a
Create Date: 2025-12-18 15:11:20.349054

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '98fc13ea3d84'
down_revision: Union[str, Sequence[str], None] = '49411765d07a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('clip_folderId_fkey', 'clip', type_='foreignkey')
    op.drop_column('clip', 'folderId')
    op.drop_table('folder')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('clip', sa.Column('folderId', sa.UUID(), autoincrement=False, nullable=True))
    op.create_foreign_key(op.f('clip_folderId_fkey'), 'clip', 'folder', ['folderId'], ['id'])
    op.create_table('folder',
    sa.Column('id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('name', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('parentId', sa.UUID(), autoincrement=False, nullable=True),
    sa.Column('category', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('createdAt', sa.BIGINT(), autoincrement=False, nullable=False),
    sa.Column('user_id', sa.UUID(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['parentId'], ['folder.id'], name=op.f('folder_parentId_fkey')),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], name=op.f('folder_user_id_fkey')),
    sa.PrimaryKeyConstraint('id', name=op.f('folder_pkey'))
    )
    # ### end Alembic commands ###
