"""Add category to tag

Revision ID: a56b7c22346f
Revises: 6f97a37272b1
Create Date: 2025-12-13 19:23:01.002385

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel

# revision identifiers, used by Alembic.
revision: str = 'a56b7c22346f'
down_revision: Union[str, Sequence[str], None] = '6f97a37272b1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tag', sa.Column('category', sqlmodel.sql.sqltypes.AutoString(), nullable=False, server_default='video'))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('tag', 'category')
    # ### end Alembic commands ###
