"""Add stripe fields to User

Revision ID: a75938c1eeed
Revises: 3811d2cf703d
Create Date: 2025-12-18 10:30:56.993495

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = 'a75938c1eeed'
down_revision: Union[str, Sequence[str], None] = '3811d2cf703d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('stripe_customer_id', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    op.add_column('user', sa.Column('subscription_status', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    op.add_column('user', sa.Column('subscription_id', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    op.create_index(op.f('ix_user_stripe_customer_id'), 'user', ['stripe_customer_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_user_stripe_customer_id'), table_name='user')
    op.drop_column('user', 'subscription_id')
    op.drop_column('user', 'subscription_status')
    op.drop_column('user', 'stripe_customer_id')
    # ### end Alembic commands ###
