"""Add moodboard table and relationships

Revision ID: c8ab64aad7e3
Revises: 33dc08c7bb10
Create Date: 2026-01-25 19:58:45.605588

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c8ab64aad7e3'
down_revision: Union[str, Sequence[str], None] = '33dc08c7bb10'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('moodboard',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('createdAt', sa.BigInteger(), nullable=False),
    sa.Column('updatedAt', sa.BigInteger(), nullable=False),
    sa.Column('user_id', sa.Uuid(), nullable=True),
    sa.Column('space_id', sa.Uuid(), nullable=True),
    sa.ForeignKeyConstraint(['space_id'], ['space.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.add_column('image', sa.Column('moodboard_id', sa.Uuid(), nullable=True))
    op.create_foreign_key(None, 'image', 'moodboard', ['moodboard_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'image', type_='foreignkey')
    op.drop_column('image', 'moodboard_id')
    op.drop_table('moodboard')
    # ### end Alembic commands ###
