"""verify_schema_sync

Revision ID: f03eb7b52ec9
Revises: f44ca305d587
Create Date: 2026-01-25 18:27:33.680909

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f03eb7b52ec9'
down_revision: Union[str, Sequence[str], None] = 'f44ca305d587'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_aiworkflow_is_public'), table_name='aiworkflow')
    op.drop_index(op.f('ix_aiworkflow_user_id'), table_name='aiworkflow')
    op.drop_index(op.f('ix_credittransaction_transaction_type'), table_name='credittransaction')
    op.drop_index(op.f('ix_credittransaction_user_id'), table_name='credittransaction')
    op.drop_index(op.f('ix_replicatemodelcache_category'), table_name='replicatemodelcache')
    op.drop_index(op.f('ix_workflowexecution_status'), table_name='workflowexecution')
    op.drop_index(op.f('ix_workflowexecution_user_id'), table_name='workflowexecution')
    op.drop_index(op.f('ix_workflowexecution_workflow_id'), table_name='workflowexecution')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('ix_workflowexecution_workflow_id'), 'workflowexecution', ['workflow_id'], unique=False)
    op.create_index(op.f('ix_workflowexecution_user_id'), 'workflowexecution', ['user_id'], unique=False)
    op.create_index(op.f('ix_workflowexecution_status'), 'workflowexecution', ['status'], unique=False)
    op.create_index(op.f('ix_replicatemodelcache_category'), 'replicatemodelcache', ['category'], unique=False)
    op.create_index(op.f('ix_credittransaction_user_id'), 'credittransaction', ['user_id'], unique=False)
    op.create_index(op.f('ix_credittransaction_transaction_type'), 'credittransaction', ['transaction_type'], unique=False)
    op.create_index(op.f('ix_aiworkflow_user_id'), 'aiworkflow', ['user_id'], unique=False)
    op.create_index(op.f('ix_aiworkflow_is_public'), 'aiworkflow', ['is_public'], unique=False)
    # ### end Alembic commands ###
